"""
40 A1 European Portuguese listening scenarios.
Each clip: one or two sentences read aloud via gTTS(lang='pt', tld='pt').
Each scenario has 2 comprehension questions — question_text in English,
answer options remain in the language being practised (Portuguese).
"""

LISTENING: list[dict] = [
    {
        "transcript": "Bom dia. Quero um café e um pão, por favor.",
        "topic": "cafe_order",
        "questions": [
            {"question_text": "What does the person want to drink?",
             "option_a": "Um chá", "option_b": "Um café", "option_c": "Um sumo", "option_d": "Uma água",
             "correct_answer": "Um café"},
            {"question_text": "What does the person want to eat?",
             "option_a": "Um bolo", "option_b": "Uma sandes", "option_c": "Um pão", "option_d": "Uma torrada",
             "correct_answer": "Um pão"},
        ],
    },
    {
        "transcript": "Desculpe, onde fica a farmácia? É ali, ao lado do banco.",
        "topic": "directions",
        "questions": [
            {"question_text": "What is the person looking for?",
             "option_a": "Um banco", "option_b": "Um hotel", "option_c": "Uma farmácia", "option_d": "Uma escola",
             "correct_answer": "Uma farmácia"},
            {"question_text": "Where is the pharmacy located?",
             "option_a": "In front of the bank", "option_b": "Next to the bank", "option_c": "Behind the bank", "option_d": "Far from the bank",
             "correct_answer": "Next to the bank"},
        ],
    },
    {
        "transcript": "O comboio para o Porto parte às oito e meia da manhã.",
        "topic": "transport",
        "questions": [
            {"question_text": "Where is the train going?",
             "option_a": "Lisboa", "option_b": "Faro", "option_c": "Porto", "option_d": "Coimbra",
             "correct_answer": "Porto"},
            {"question_text": "What time does the train depart?",
             "option_a": "At eight o'clock", "option_b": "At half past eight", "option_c": "At nine o'clock", "option_d": "At half past seven",
             "correct_answer": "At half past eight"},
        ],
    },
    {
        "transcript": "Tenho uma consulta com o médico às três da tarde.",
        "topic": "health",
        "questions": [
            {"question_text": "Who is the appointment with?",
             "option_a": "The dentist", "option_b": "The doctor", "option_c": "The nurse", "option_d": "The teacher",
             "correct_answer": "The doctor"},
            {"question_text": "What time is the appointment?",
             "option_a": "At two in the afternoon", "option_b": "At three in the afternoon", "option_c": "At four in the afternoon", "option_d": "At three in the morning",
             "correct_answer": "At three in the afternoon"},
        ],
    },
    {
        "transcript": "Hoje é sexta-feira. Vamos jantar fora com os amigos.",
        "topic": "daily_life",
        "questions": [
            {"question_text": "What day is it today?",
             "option_a": "Thursday", "option_b": "Saturday", "option_c": "Friday", "option_d": "Sunday",
             "correct_answer": "Friday"},
            {"question_text": "What are they going to do tonight?",
             "option_a": "Stay at home", "option_b": "Go to the cinema", "option_c": "Eat out", "option_d": "Study",
             "correct_answer": "Eat out"},
        ],
    },
    {
        "transcript": "Preciso de um quarto para duas noites, por favor. Com pequeno-almoço.",
        "topic": "hotel",
        "questions": [
            {"question_text": "How many nights is the room for?",
             "option_a": "One night", "option_b": "Three nights", "option_c": "Two nights", "option_d": "Four nights",
             "correct_answer": "Two nights"},
            {"question_text": "What else does the person request besides the room?",
             "option_a": "Dinner", "option_b": "Breakfast", "option_c": "Lunch", "option_d": "Swimming pool",
             "correct_answer": "Breakfast"},
        ],
    },
    {
        "transcript": "O supermercado está fechado ao domingo. Abre às nove de segunda a sábado.",
        "topic": "shopping",
        "questions": [
            {"question_text": "When is the supermarket closed?",
             "option_a": "On Saturday", "option_b": "On Sunday", "option_c": "On Monday", "option_d": "On Friday",
             "correct_answer": "On Sunday"},
            {"question_text": "What time does the supermarket open on weekdays?",
             "option_a": "At eight", "option_b": "At ten", "option_c": "At nine", "option_d": "At seven",
             "correct_answer": "At nine"},
        ],
    },
    {
        "transcript": "Moro em Lisboa há dois anos. A minha família é do Porto.",
        "topic": "personal_info",
        "questions": [
            {"question_text": "Where does the person live now?",
             "option_a": "In Porto", "option_b": "In Faro", "option_c": "In Lisbon", "option_d": "In Coimbra",
             "correct_answer": "In Lisbon"},
            {"question_text": "Where is the person's family from?",
             "option_a": "From Lisbon", "option_b": "From Porto", "option_c": "From Braga", "option_d": "From Évora",
             "correct_answer": "From Porto"},
        ],
    },
    {
        "transcript": "Quero comprar uma camisola azul. Qual é o preço?",
        "topic": "shopping",
        "questions": [
            {"question_text": "What does the person want to buy?",
             "option_a": "A red jumper", "option_b": "A blue jumper", "option_c": "A blue jacket", "option_d": "A blue skirt",
             "correct_answer": "A blue jumper"},
            {"question_text": "What does the person ask about?",
             "option_a": "The size", "option_b": "The colour", "option_c": "The price", "option_d": "The brand",
             "correct_answer": "The price"},
        ],
    },
    {
        "transcript": "Está muito calor hoje. Vamos à praia depois do almoço.",
        "topic": "weather",
        "questions": [
            {"question_text": "How is the weather today?",
             "option_a": "Cold", "option_b": "Rainy", "option_c": "Snowy", "option_d": "Hot",
             "correct_answer": "Hot"},
            {"question_text": "When are they going to the beach?",
             "option_a": "In the morning", "option_b": "After breakfast", "option_c": "After lunch", "option_d": "At night",
             "correct_answer": "After lunch"},
        ],
    },
    {
        "transcript": "O meu nome é Ana. Sou professora de inglês numa escola primária.",
        "topic": "personal_info",
        "questions": [
            {"question_text": "What is the person's name?",
             "option_a": "Maria", "option_b": "Sara", "option_c": "Ana", "option_d": "Joana",
             "correct_answer": "Ana"},
            {"question_text": "What is Ana's profession?",
             "option_a": "Doctor", "option_b": "English teacher", "option_c": "Nurse", "option_d": "Portuguese teacher",
             "correct_answer": "English teacher"},
        ],
    },
    {
        "transcript": "Por favor, pode repetir mais devagar? Não percebi bem.",
        "topic": "communication",
        "questions": [
            {"question_text": "What does the person ask for?",
             "option_a": "To speak louder", "option_b": "To repeat more slowly", "option_c": "To write it down", "option_d": "To translate",
             "correct_answer": "To repeat more slowly"},
            {"question_text": "Why does the person make this request?",
             "option_a": "Because of too much noise", "option_b": "Because they did not understand well", "option_c": "Because they are deaf", "option_d": "Because they want to record it",
             "correct_answer": "Because they did not understand well"},
        ],
    },
    {
        "transcript": "Vou ao mercado comprar fruta e legumes. Preciso de tomates e alface.",
        "topic": "shopping",
        "questions": [
            {"question_text": "Where is the person going?",
             "option_a": "To the supermarket", "option_b": "To the market", "option_c": "To the shop", "option_d": "To the bank",
             "correct_answer": "To the market"},
            {"question_text": "Which vegetables does the person need?",
             "option_a": "Carrots and potatoes", "option_b": "Tomatoes and lettuce", "option_c": "Onions and garlic", "option_d": "Bananas and oranges",
             "correct_answer": "Tomatoes and lettuce"},
        ],
    },
    {
        "transcript": "Tenho saudades da minha família. Falo com eles todos os domingos.",
        "topic": "family",
        "questions": [
            {"question_text": "Who does the person miss?",
             "option_a": "Friends", "option_b": "Family", "option_c": "Colleagues", "option_d": "Neighbours",
             "correct_answer": "Family"},
            {"question_text": "When does the person talk to their family?",
             "option_a": "Every Saturday", "option_b": "Every Sunday", "option_c": "Every day", "option_d": "Once a month",
             "correct_answer": "Every Sunday"},
        ],
    },
    {
        "transcript": "A aula de português começa às dez horas e acaba ao meio-dia.",
        "topic": "education",
        "questions": [
            {"question_text": "When does the Portuguese class start?",
             "option_a": "At nine", "option_b": "At ten", "option_c": "At eleven", "option_d": "At noon",
             "correct_answer": "At ten"},
            {"question_text": "When does the class end?",
             "option_a": "At ten", "option_b": "At eleven", "option_c": "At noon", "option_d": "At one",
             "correct_answer": "At noon"},
        ],
    },
    {
        "transcript": "Quero reservar uma mesa para quatro pessoas para sábado à noite.",
        "topic": "restaurant",
        "questions": [
            {"question_text": "For how many people is the reservation?",
             "option_a": "Two people", "option_b": "Three people", "option_c": "Four people", "option_d": "Five people",
             "correct_answer": "Four people"},
            {"question_text": "When is the reservation?",
             "option_a": "Friday evening", "option_b": "Saturday lunch", "option_c": "Saturday evening", "option_d": "Sunday evening",
             "correct_answer": "Saturday evening"},
        ],
    },
    {
        "transcript": "O meu pai trabalha num hospital. A minha mãe é professora.",
        "topic": "family",
        "questions": [
            {"question_text": "Where does the father work?",
             "option_a": "At a school", "option_b": "At a company", "option_c": "At a hospital", "option_d": "At a bank",
             "correct_answer": "At a hospital"},
            {"question_text": "What is the mother's profession?",
             "option_a": "Doctor", "option_b": "Teacher", "option_c": "Nurse", "option_d": "Lawyer",
             "correct_answer": "Teacher"},
        ],
    },
    {
        "transcript": "Não me sinto bem. Tenho febre e dores de cabeça.",
        "topic": "health",
        "questions": [
            {"question_text": "How does the person feel?",
             "option_a": "Very well", "option_b": "Tired", "option_c": "Unwell", "option_d": "Happy",
             "correct_answer": "Unwell"},
            {"question_text": "What symptoms does the person have?",
             "option_a": "Stomach ache", "option_b": "Fever and headache", "option_c": "Cough and cold", "option_d": "Back pain",
             "correct_answer": "Fever and headache"},
        ],
    },
    {
        "transcript": "Gosto muito de Portugal. O tempo é bom e a comida é deliciosa.",
        "topic": "opinion",
        "questions": [
            {"question_text": "According to the speaker, how is the weather in Portugal?",
             "option_a": "Very cold", "option_b": "Bad", "option_c": "Good", "option_d": "Rainy",
             "correct_answer": "Good"},
            {"question_text": "What does the person most appreciate about Portugal?",
             "option_a": "The culture and museums", "option_b": "The weather and food", "option_c": "The beaches and sea", "option_d": "The language",
             "correct_answer": "The weather and food"},
        ],
    },
    {
        "transcript": "Ao fim de semana gosto de andar de bicicleta no parque.",
        "topic": "leisure",
        "questions": [
            {"question_text": "When does the person do this activity?",
             "option_a": "During the week", "option_b": "At the weekend", "option_c": "Every day", "option_d": "Early in the morning",
             "correct_answer": "At the weekend"},
            {"question_text": "Where does the person cycle?",
             "option_a": "At the beach", "option_b": "On the street", "option_c": "In the park", "option_d": "At school",
             "correct_answer": "In the park"},
        ],
    },
    {
        "transcript": "Tenho vinte e cinco anos e sou de Coimbra.",
        "topic": "personal_info",
        "questions": [
            {"question_text": "How old is the person?",
             "option_a": "Twenty years old", "option_b": "Twenty-two years old", "option_c": "Thirty years old", "option_d": "Twenty-five years old",
             "correct_answer": "Twenty-five years old"},
            {"question_text": "Where is the person from?",
             "option_a": "Lisbon", "option_b": "Porto", "option_c": "Coimbra", "option_d": "Faro",
             "correct_answer": "Coimbra"},
        ],
    },
    {
        "transcript": "O restaurante serve peixe fresco todos os dias. O bacalhau é muito bom.",
        "topic": "restaurant",
        "questions": [
            {"question_text": "What does the restaurant serve every day?",
             "option_a": "Grilled meat", "option_b": "Fresh fish", "option_c": "Vegetable soup", "option_d": "Various desserts",
             "correct_answer": "Fresh fish"},
            {"question_text": "Which dish is recommended?",
             "option_a": "Sardine", "option_b": "Octopus", "option_c": "Codfish", "option_d": "Tuna",
             "correct_answer": "Codfish"},
        ],
    },
    {
        "transcript": "O bilhete de comboio custa doze euros. Pago com cartão.",
        "topic": "transport",
        "questions": [
            {"question_text": "How much does the train ticket cost?",
             "option_a": "Ten euros", "option_b": "Eleven euros", "option_c": "Twelve euros", "option_d": "Fifteen euros",
             "correct_answer": "Twelve euros"},
            {"question_text": "How does the person pay?",
             "option_a": "In cash", "option_b": "By cheque", "option_c": "By card", "option_d": "By phone",
             "correct_answer": "By card"},
        ],
    },
    {
        "transcript": "A minha irmã tem um gato preto e um cão branco.",
        "topic": "family",
        "questions": [
            {"question_text": "What animals does the sister have?",
             "option_a": "Two dogs", "option_b": "Two cats", "option_c": "A cat and a dog", "option_d": "A dog and a rabbit",
             "correct_answer": "A cat and a dog"},
            {"question_text": "What colour is the cat?",
             "option_a": "White", "option_b": "Grey", "option_c": "Brown", "option_d": "Black",
             "correct_answer": "Black"},
        ],
    },
    {
        "transcript": "Vivo num apartamento no quinto andar. Não há elevador.",
        "topic": "housing",
        "questions": [
            {"question_text": "Where does the person live?",
             "option_a": "In a house", "option_b": "In an apartment", "option_c": "In a hotel", "option_d": "In a hostel",
             "correct_answer": "In an apartment"},
            {"question_text": "What is the problem with the building?",
             "option_a": "No hot water", "option_b": "No lift", "option_c": "No electricity", "option_d": "No parking",
             "correct_answer": "No lift"},
        ],
    },
    {
        "transcript": "Falo um pouco de português. Estudo há seis meses.",
        "topic": "education",
        "questions": [
            {"question_text": "What language does the person study?",
             "option_a": "English", "option_b": "French", "option_c": "Spanish", "option_d": "Portuguese",
             "correct_answer": "Portuguese"},
            {"question_text": "How long has the person been studying?",
             "option_a": "Three months", "option_b": "Six months", "option_c": "One year", "option_d": "Two years",
             "correct_answer": "Six months"},
        ],
    },
    {
        "transcript": "Amanhã vou ao aeroporto. O meu voo parte às sete da manhã.",
        "topic": "transport",
        "questions": [
            {"question_text": "Where is the person going tomorrow?",
             "option_a": "To the train station", "option_b": "To the airport", "option_c": "To the bus stop", "option_d": "To the port",
             "correct_answer": "To the airport"},
            {"question_text": "What time does the flight depart?",
             "option_a": "At six in the morning", "option_b": "At eight in the morning", "option_c": "At seven in the morning", "option_d": "At seven in the evening",
             "correct_answer": "At seven in the morning"},
        ],
    },
    {
        "transcript": "O Pedro e a Joana são casados. Têm dois filhos.",
        "topic": "family",
        "questions": [
            {"question_text": "What is the relationship between Pedro and Joana?",
             "option_a": "They are siblings", "option_b": "They are friends", "option_c": "They are married", "option_d": "They are colleagues",
             "correct_answer": "They are married"},
            {"question_text": "How many children do they have?",
             "option_a": "One child", "option_b": "Three children", "option_c": "Four children", "option_d": "Two children",
             "correct_answer": "Two children"},
        ],
    },
    {
        "transcript": "Quero enviar este pacote para o Brasil. Qual é o preço?",
        "topic": "post_office",
        "questions": [
            {"question_text": "What does the person want to do?",
             "option_a": "Receive a package", "option_b": "Send a package", "option_c": "Buy stamps", "option_d": "Withdraw money",
             "correct_answer": "Send a package"},
            {"question_text": "Where is the package going?",
             "option_a": "To Portugal", "option_b": "To France", "option_c": "To Brazil", "option_d": "To Spain",
             "correct_answer": "To Brazil"},
        ],
    },
    {
        "transcript": "Hoje à tarde fui às compras. Comprei sapatos novos.",
        "topic": "shopping",
        "questions": [
            {"question_text": "When did the person go shopping?",
             "option_a": "In the morning", "option_b": "In the afternoon", "option_c": "At night", "option_d": "Yesterday",
             "correct_answer": "In the afternoon"},
            {"question_text": "What did the person buy?",
             "option_a": "A new bag", "option_b": "New clothes", "option_c": "New shoes", "option_d": "A new hat",
             "correct_answer": "New shoes"},
        ],
    },
    {
        "transcript": "É proibido fumar neste edifício. Obrigado pela compreensão.",
        "topic": "rules",
        "questions": [
            {"question_text": "What is prohibited in this building?",
             "option_a": "Eating", "option_b": "Drinking", "option_c": "Smoking", "option_d": "Talking",
             "correct_answer": "Smoking"},
            {"question_text": "What does the message say at the end?",
             "option_a": "Please leave", "option_b": "Thank you for your understanding", "option_c": "Good luck", "option_d": "Goodbye",
             "correct_answer": "Thank you for your understanding"},
        ],
    },
    {
        "transcript": "Preciso de mudar dinheiro. Onde fica o banco mais próximo?",
        "topic": "bank",
        "questions": [
            {"question_text": "What does the person need to do?",
             "option_a": "Open an account", "option_b": "Pay a bill", "option_c": "Exchange money", "option_d": "Withdraw money",
             "correct_answer": "Exchange money"},
            {"question_text": "What is the person looking for?",
             "option_a": "An ATM", "option_b": "The nearest bank", "option_c": "A pharmacy", "option_d": "The post office",
             "correct_answer": "The nearest bank"},
        ],
    },
    {
        "transcript": "No verão faço férias em Portugal. Adoro a praia e o sol.",
        "topic": "holidays",
        "questions": [
            {"question_text": "When does the person go on holiday?",
             "option_a": "In winter", "option_b": "In spring", "option_c": "In autumn", "option_d": "In summer",
             "correct_answer": "In summer"},
            {"question_text": "What does the person love?",
             "option_a": "The mountains and countryside", "option_b": "The beach and sun", "option_c": "The city and culture", "option_d": "The cold and snow",
             "correct_answer": "The beach and sun"},
        ],
    },
    {
        "transcript": "O João levanta-se às sete horas e toma o pequeno-almoço em casa.",
        "topic": "daily_routine",
        "questions": [
            {"question_text": "What time does João wake up?",
             "option_a": "At six", "option_b": "At eight", "option_c": "At seven", "option_d": "At half past seven",
             "correct_answer": "At seven"},
            {"question_text": "Where does João have breakfast?",
             "option_a": "At the café", "option_b": "At the office", "option_c": "At home", "option_d": "At school",
             "correct_answer": "At home"},
        ],
    },
    {
        "transcript": "Boa tarde. Tem um quarto livre para esta noite?",
        "topic": "hotel",
        "questions": [
            {"question_text": "Which greeting is used?",
             "option_a": "Good morning", "option_b": "Good night", "option_c": "Good afternoon", "option_d": "Hello",
             "correct_answer": "Good afternoon"},
            {"question_text": "When does the person need the room?",
             "option_a": "For tomorrow", "option_b": "For the weekend", "option_c": "For tonight", "option_d": "For next week",
             "correct_answer": "For tonight"},
        ],
    },
    {
        "transcript": "Gosto muito de ler. Leio um livro por mês, normalmente.",
        "topic": "hobbies",
        "questions": [
            {"question_text": "What does the person enjoy doing?",
             "option_a": "Listening to music", "option_b": "Watching television", "option_c": "Reading", "option_d": "Playing football",
             "correct_answer": "Reading"},
            {"question_text": "How often does the person read a book?",
             "option_a": "Once a week", "option_b": "Every day", "option_c": "Once a month", "option_d": "Once a year",
             "correct_answer": "Once a month"},
        ],
    },
    {
        "transcript": "Há autocarro para o aeroporto? Sim, de quinze em quinze minutos.",
        "topic": "transport",
        "questions": [
            {"question_text": "Where does the bus go?",
             "option_a": "To the train station", "option_b": "To the airport", "option_c": "To the centre", "option_d": "To the beach",
             "correct_answer": "To the airport"},
            {"question_text": "How often does the bus come?",
             "option_a": "Every ten minutes", "option_b": "Every twenty minutes", "option_c": "Every fifteen minutes", "option_d": "Every half hour",
             "correct_answer": "Every fifteen minutes"},
        ],
    },
    {
        "transcript": "A minha casa tem três quartos, uma sala e uma cozinha grande.",
        "topic": "housing",
        "questions": [
            {"question_text": "How many bedrooms does the house have?",
             "option_a": "Two bedrooms", "option_b": "Four bedrooms", "option_c": "Three bedrooms", "option_d": "One bedroom",
             "correct_answer": "Three bedrooms"},
            {"question_text": "What is the kitchen like?",
             "option_a": "Small", "option_b": "Large", "option_c": "Modern", "option_d": "New",
             "correct_answer": "Large"},
        ],
    },
    {
        "transcript": "No Portugal, o Natal é a vinte e cinco de dezembro.",
        "topic": "culture",
        "questions": [
            {"question_text": "When is Christmas in Portugal?",
             "option_a": "On the 24th of December", "option_b": "On the 25th of December", "option_c": "On the 26th of December", "option_d": "On the 1st of January",
             "correct_answer": "On the 25th of December"},
            {"question_text": "Which country does the clip mention?",
             "option_a": "Brazil", "option_b": "Portugal", "option_c": "Spain", "option_d": "France",
             "correct_answer": "Portugal"},
        ],
    },
    {
        "transcript": "Trabalho das nove da manhã às cinco da tarde, de segunda a sexta.",
        "topic": "work",
        "questions": [
            {"question_text": "What time does work start?",
             "option_a": "At eight", "option_b": "At ten", "option_c": "At nine", "option_d": "At half past eight",
             "correct_answer": "At nine"},
            {"question_text": "How many days a week does the person work?",
             "option_a": "Four days", "option_b": "Six days", "option_c": "Seven days", "option_d": "Five days",
             "correct_answer": "Five days"},
        ],
    },
    {
        "transcript": "Pode me dar um copo de água, por favor? Claro, com muito gosto.",
        "topic": "cafe_order",
        "questions": [
            {"question_text": "What does the person ask for?",
             "option_a": "A glass of milk", "option_b": "A glass of juice", "option_c": "A glass of water", "option_d": "A glass of wine",
             "correct_answer": "A glass of water"},
            {"question_text": "How does the employee respond?",
             "option_a": "Sorry, we don't have any", "option_b": "Of course, with pleasure", "option_c": "That's not possible", "option_d": "One moment, please",
             "correct_answer": "Of course, with pleasure"},
        ],
    },
]
