"""
27 A1 European Portuguese reading passages (2–3 sentences each).
Each passage has 5 comprehension questions.
question_text is in English; answer options are in the language being practised.
"""

PASSAGES: list[dict] = [
    {
        "title": "No café",
        "topic": "daily_life",
        "text": "A Joana entra no café e pede um galão e uma torrada. A empregada traz o pedido e a Joana paga dois euros e cinquenta. Ela fica a ler o jornal enquanto bebe o galão.",
        "questions": [
            {"question_text": "What does Joana order to drink?",
             "option_a": "Um café", "option_b": "Um sumo", "option_c": "Um galão", "option_d": "Um chá",
             "correct_answer": "Um galão"},
            {"question_text": "What does Joana order to eat?",
             "option_a": "Um bolo", "option_b": "Uma torrada", "option_c": "Um pão", "option_d": "Um pastel",
             "correct_answer": "Uma torrada"},
            {"question_text": "How much does Joana pay?",
             "option_a": "Um euro e cinquenta", "option_b": "Três euros", "option_c": "Dois euros e cinquenta", "option_d": "Dois euros",
             "correct_answer": "Dois euros e cinquenta"},
            {"question_text": "Who brings the order?",
             "option_a": "A Joana", "option_b": "A empregada", "option_c": "O gerente", "option_d": "Um amigo",
             "correct_answer": "A empregada"},
            {"question_text": "What does Joana do while she drinks?",
             "option_a": "Fala ao telemóvel", "option_b": "Estuda", "option_c": "Lê o jornal", "option_d": "Come um bolo",
             "correct_answer": "Lê o jornal"},
        ],
    },
    {
        "title": "O comboio para Lisboa",
        "topic": "transport",
        "text": "O António compra um bilhete de comboio para Lisboa. O comboio parte às dez horas e chega às onze e meia. A viagem custa quinze euros.",
        "questions": [
            {"question_text": "Where is António going?",
             "option_a": "Porto", "option_b": "Coimbra", "option_c": "Lisboa", "option_d": "Faro",
             "correct_answer": "Lisboa"},
            {"question_text": "What time does the train depart?",
             "option_a": "Às nove horas", "option_b": "Às dez horas", "option_c": "Às onze horas", "option_d": "Às dez e meia",
             "correct_answer": "Às dez horas"},
            {"question_text": "What time does the train arrive?",
             "option_a": "Às onze horas", "option_b": "Às onze e meia", "option_c": "Às doze horas", "option_d": "Ao meio-dia e meia",
             "correct_answer": "Às onze e meia"},
            {"question_text": "How much does the journey cost?",
             "option_a": "Dez euros", "option_b": "Doze euros", "option_c": "Vinte euros", "option_d": "Quinze euros",
             "correct_answer": "Quinze euros"},
            {"question_text": "What does António buy?",
             "option_a": "Um bilhete de autocarro", "option_b": "Um bilhete de avião", "option_c": "Um bilhete de comboio", "option_d": "Um bilhete de metro",
             "correct_answer": "Um bilhete de comboio"},
        ],
    },
    {
        "title": "A família da Ana",
        "topic": "family",
        "text": "A Ana tem trinta anos e mora em Lisboa com o marido e dois filhos. O marido chama-se Pedro e trabalha num hospital. Os filhos têm cinco e oito anos.",
        "questions": [
            {"question_text": "How old is Ana?",
             "option_a": "Vinte anos", "option_b": "Vinte e cinco anos", "option_c": "Trinta anos", "option_d": "Trinta e cinco anos",
             "correct_answer": "Trinta anos"},
            {"question_text": "Where does Ana live?",
             "option_a": "No Porto", "option_b": "Em Lisboa", "option_c": "Em Coimbra", "option_d": "Em Braga",
             "correct_answer": "Em Lisboa"},
            {"question_text": "What is Ana's husband's name?",
             "option_a": "João", "option_b": "Rui", "option_c": "Pedro", "option_d": "André",
             "correct_answer": "Pedro"},
            {"question_text": "Where does Pedro work?",
             "option_a": "Numa escola", "option_b": "Num banco", "option_c": "Numa empresa", "option_d": "Num hospital",
             "correct_answer": "Num hospital"},
            {"question_text": "How many children does Ana have?",
             "option_a": "Um filho", "option_b": "Dois filhos", "option_c": "Três filhos", "option_d": "Quatro filhos",
             "correct_answer": "Dois filhos"},
        ],
    },
    {
        "title": "No supermercado",
        "topic": "shopping",
        "text": "A Marta vai ao supermercado comprar comida para o jantar. Compra frango, batatas e salada. Paga com cartão à saída.",
        "questions": [
            {"question_text": "Why does Marta go to the supermarket?",
             "option_a": "Para comprar roupa", "option_b": "Para comprar comida para o jantar", "option_c": "Para pagar uma conta", "option_d": "Para levantar dinheiro",
             "correct_answer": "Para comprar comida para o jantar"},
            {"question_text": "What does Marta buy?",
             "option_a": "Peixe, arroz e sopa", "option_b": "Carne, pão e fruta", "option_c": "Frango, batatas e salada", "option_d": "Bacalhau, cebola e tomate",
             "correct_answer": "Frango, batatas e salada"},
            {"question_text": "How does Marta pay?",
             "option_a": "Em dinheiro", "option_b": "Com cheque", "option_c": "Com cartão", "option_d": "Não paga",
             "correct_answer": "Com cartão"},
            {"question_text": "Where does Marta pay?",
             "option_a": "Na entrada", "option_b": "À saída", "option_c": "No balcão", "option_d": "Online",
             "correct_answer": "À saída"},
            {"question_text": "Which meal is the food for?",
             "option_a": "Pequeno-almoço", "option_b": "Almoço", "option_c": "Lanche", "option_d": "Jantar",
             "correct_answer": "Jantar"},
        ],
    },
    {
        "title": "O tempo em Portugal",
        "topic": "weather",
        "text": "Em Portugal o verão é muito quente e seco. O inverno é frio e chuvoso no norte. No sul, o clima é mais ameno durante o ano todo.",
        "questions": [
            {"question_text": "What is summer like in Portugal?",
             "option_a": "Frio e chuvoso", "option_b": "Ameno e ventoso", "option_c": "Muito quente e seco", "option_d": "Com neve",
             "correct_answer": "Muito quente e seco"},
            {"question_text": "What is winter like in the north of Portugal?",
             "option_a": "Quente e seco", "option_b": "Frio e chuvoso", "option_c": "Ameno e seco", "option_d": "Com neve sempre",
             "correct_answer": "Frio e chuvoso"},
            {"question_text": "Where is the climate milder?",
             "option_a": "No norte", "option_b": "No centro", "option_c": "No sul", "option_d": "Nas ilhas",
             "correct_answer": "No sul"},
            {"question_text": "How is the climate in the south throughout the year?",
             "option_a": "Muito quente sempre", "option_b": "Muito frio sempre", "option_c": "Mais ameno durante o ano todo", "option_d": "Com muita chuva",
             "correct_answer": "Mais ameno durante o ano todo"},
            {"question_text": "Which country does the text describe?",
             "option_a": "Espanha", "option_b": "Brasil", "option_c": "Portugal", "option_d": "França",
             "correct_answer": "Portugal"},
        ],
    },
    {
        "title": "O médico",
        "topic": "health",
        "text": "O Manuel não se sente bem. Tem dores de cabeça e febre. Vai ao médico que lhe receita um medicamento e recomenda repouso.",
        "questions": [
            {"question_text": "How does Manuel feel?",
             "option_a": "Muito bem", "option_b": "Não se sente bem", "option_c": "Cansado mas saudável", "option_d": "Feliz e bem-disposto",
             "correct_answer": "Não se sente bem"},
            {"question_text": "What symptoms does Manuel have?",
             "option_a": "Dores de barriga e tosse", "option_b": "Febre e dores de costas", "option_c": "Dores de cabeça e febre", "option_d": "Dores de garganta e cansaço",
             "correct_answer": "Dores de cabeça e febre"},
            {"question_text": "What does Manuel do?",
             "option_a": "Vai à farmácia", "option_b": "Vai ao hospital", "option_c": "Fica em casa", "option_d": "Vai ao médico",
             "correct_answer": "Vai ao médico"},
            {"question_text": "What does the doctor give Manuel?",
             "option_a": "Vitaminas", "option_b": "Um medicamento", "option_c": "Um atestado", "option_d": "Uma injecção",
             "correct_answer": "Um medicamento"},
            {"question_text": "What else does the doctor recommend besides medication?",
             "option_a": "Exercício físico", "option_b": "Repouso", "option_c": "Uma dieta", "option_d": "Água morna",
             "correct_answer": "Repouso"},
        ],
    },
    {
        "title": "Uma manhã típica",
        "topic": "daily_routine",
        "text": "A Sara acorda às sete horas e toma banho. Depois toma o pequeno-almoço com o marido. Às oito e meia sai de casa para o trabalho.",
        "questions": [
            {"question_text": "What time does Sara wake up?",
             "option_a": "Às seis horas", "option_b": "Às sete horas", "option_c": "Às oito horas", "option_d": "Às sete e meia",
             "correct_answer": "Às sete horas"},
            {"question_text": "What does Sara do after waking up?",
             "option_a": "Toma o pequeno-almoço", "option_b": "Sai de casa", "option_c": "Toma banho", "option_d": "Lê o jornal",
             "correct_answer": "Toma banho"},
            {"question_text": "Who does Sara have breakfast with?",
             "option_a": "Sozinha", "option_b": "Com os filhos", "option_c": "Com o marido", "option_d": "Com a mãe",
             "correct_answer": "Com o marido"},
            {"question_text": "What time does Sara leave for work?",
             "option_a": "Às oito horas", "option_b": "Às oito e meia", "option_c": "Às nove horas", "option_d": "Às sete e meia",
             "correct_answer": "Às oito e meia"},
            {"question_text": "Where does Sara go at half past eight?",
             "option_a": "Para a escola", "option_b": "Para o mercado", "option_c": "Para o trabalho", "option_d": "Para o médico",
             "correct_answer": "Para o trabalho"},
        ],
    },
    {
        "title": "O hotel em Lisboa",
        "topic": "tourism",
        "text": "O Carlos reservou um quarto num hotel no centro de Lisboa. O hotel tem piscina e pequeno-almoço incluído. Fica a cinco minutos do museu.",
        "questions": [
            {"question_text": "What did Carlos book?",
             "option_a": "Um apartamento", "option_b": "Um quarto num hotel", "option_c": "Uma casa de campo", "option_d": "Um albergue",
             "correct_answer": "Um quarto num hotel"},
            {"question_text": "Where is the hotel located?",
             "option_a": "No aeroporto", "option_b": "Na periferia", "option_c": "No centro de Lisboa", "option_d": "Junto à praia",
             "correct_answer": "No centro de Lisboa"},
            {"question_text": "What facilities does the hotel have?",
             "option_a": "Ginásio e spa", "option_b": "Piscina e pequeno-almoço incluído", "option_c": "Restaurante e bar", "option_d": "Estacionamento gratuito",
             "correct_answer": "Piscina e pequeno-almoço incluído"},
            {"question_text": "How far is the museum from the hotel?",
             "option_a": "A dois minutos", "option_b": "A dez minutos", "option_c": "A cinco minutos", "option_d": "A quinze minutos",
             "correct_answer": "A cinco minutos"},
            {"question_text": "Is breakfast included?",
             "option_a": "Não, é extra", "option_b": "Sim, está incluído", "option_c": "Não há pequeno-almoço", "option_d": "Só ao fim de semana",
             "correct_answer": "Sim, está incluído"},
        ],
    },
    {
        "title": "A escola do Miguel",
        "topic": "education",
        "text": "O Miguel tem doze anos e anda numa escola em Coimbra. Gosta muito de matemática e inglês. Todos os dias vai a pé para a escola com os amigos.",
        "questions": [
            {"question_text": "How old is Miguel?",
             "option_a": "Dez anos", "option_b": "Onze anos", "option_c": "Doze anos", "option_d": "Treze anos",
             "correct_answer": "Doze anos"},
            {"question_text": "Where is Miguel's school?",
             "option_a": "Em Lisboa", "option_b": "Em Coimbra", "option_c": "No Porto", "option_d": "Em Braga",
             "correct_answer": "Em Coimbra"},
            {"question_text": "Which subjects does Miguel enjoy?",
             "option_a": "Português e história", "option_b": "Ciências e desporto", "option_c": "Matemática e inglês", "option_d": "Arte e música",
             "correct_answer": "Matemática e inglês"},
            {"question_text": "How does Miguel get to school?",
             "option_a": "De carro", "option_b": "De autocarro", "option_c": "A pé", "option_d": "De bicicleta",
             "correct_answer": "A pé"},
            {"question_text": "Who does Miguel walk to school with?",
             "option_a": "Com os pais", "option_b": "Sozinho", "option_c": "Com os irmãos", "option_d": "Com os amigos",
             "correct_answer": "Com os amigos"},
        ],
    },
    {
        "title": "O restaurante",
        "topic": "food",
        "text": "O restaurante 'A Tasca' fica na Rua dos Correeiros. Serve pratos típicos portugueses como bacalhau e caldo verde. Está aberto todos os dias, menos à segunda-feira.",
        "questions": [
            {"question_text": "What is the restaurant called?",
             "option_a": "O Garrote", "option_b": "A Tasca", "option_c": "O Bacalhau", "option_d": "A Taberna",
             "correct_answer": "A Tasca"},
            {"question_text": "Where is the restaurant?",
             "option_a": "Na Rua dos Flores", "option_b": "Na Avenida Principal", "option_c": "Na Rua dos Correeiros", "option_d": "Na Praça do Comércio",
             "correct_answer": "Na Rua dos Correeiros"},
            {"question_text": "What type of food does it serve?",
             "option_a": "Comida italiana", "option_b": "Pratos típicos portugueses", "option_c": "Comida internacional", "option_d": "Pratos vegetarianos",
             "correct_answer": "Pratos típicos portugueses"},
            {"question_text": "Which of the following dishes is mentioned?",
             "option_a": "Polvo à lagareiro", "option_b": "Sardinha assada", "option_c": "Bacalhau", "option_d": "Cozido à portuguesa",
             "correct_answer": "Bacalhau"},
            {"question_text": "When is the restaurant closed?",
             "option_a": "Ao domingo", "option_b": "Ao sábado", "option_c": "À segunda-feira", "option_d": "À sexta-feira",
             "correct_answer": "À segunda-feira"},
        ],
    },
    {
        "title": "As férias de verão",
        "topic": "holidays",
        "text": "A família Sousa vai de férias ao Algarve em agosto. Ficam numa casa alugada junto à praia durante duas semanas. Os filhos adoram nadar no mar.",
        "questions": [
            {"question_text": "Where does the Sousa family go on holiday?",
             "option_a": "À Madeira", "option_b": "Aos Açores", "option_c": "Ao Alentejo", "option_d": "Ao Algarve",
             "correct_answer": "Ao Algarve"},
            {"question_text": "Which month do they go on holiday?",
             "option_a": "Julho", "option_b": "Agosto", "option_c": "Junho", "option_d": "Setembro",
             "correct_answer": "Agosto"},
            {"question_text": "Where are they staying?",
             "option_a": "Num hotel", "option_b": "Num albergue", "option_c": "Numa casa alugada", "option_d": "Em casa de familiares",
             "correct_answer": "Numa casa alugada"},
            {"question_text": "How long is the holiday?",
             "option_a": "Uma semana", "option_b": "Três semanas", "option_c": "Duas semanas", "option_d": "Um mês",
             "correct_answer": "Duas semanas"},
            {"question_text": "What do the children love doing?",
             "option_a": "Jogar futebol", "option_b": "Andar de bicicleta", "option_c": "Nadar no mar", "option_d": "Ler livros",
             "correct_answer": "Nadar no mar"},
        ],
    },
    {
        "title": "O mercado de Barcelos",
        "topic": "culture",
        "text": "O mercado de Barcelos é um dos maiores mercados ao ar livre de Portugal. Acontece todas as quintas-feiras e vende-se de tudo: fruta, roupa, cerâmica e animais.",
        "questions": [
            {"question_text": "Where is this market located?",
             "option_a": "Lisboa", "option_b": "Braga", "option_c": "Barcelos", "option_d": "Porto",
             "correct_answer": "Barcelos"},
            {"question_text": "When does the market take place?",
             "option_a": "Às segundas-feiras", "option_b": "Às quintas-feiras", "option_c": "Aos sábados", "option_d": "Todos os dias",
             "correct_answer": "Às quintas-feiras"},
            {"question_text": "How is the market described?",
             "option_a": "Um dos menores de Portugal", "option_b": "Um dos maiores ao ar livre", "option_c": "Só de cerâmica", "option_d": "Só de alimentação",
             "correct_answer": "Um dos maiores ao ar livre"},
            {"question_text": "What is sold at the market?",
             "option_a": "Só fruta e legumes", "option_b": "Só roupa e sapatos", "option_c": "Fruta, roupa, cerâmica e animais", "option_d": "Livros e artesanato",
             "correct_answer": "Fruta, roupa, cerâmica e animais"},
            {"question_text": "Is the market indoors or outdoors?",
             "option_a": "Coberto", "option_b": "Ao ar livre", "option_c": "Semi-coberto", "option_d": "O texto não diz",
             "correct_answer": "Ao ar livre"},
        ],
    },
    {
        "title": "O apartamento da Inês",
        "topic": "housing",
        "text": "A Inês tem um apartamento pequeno mas confortável no segundo andar. Tem dois quartos, uma sala e uma cozinha nova. Paga quinhentos euros de renda por mês.",
        "questions": [
            {"question_text": "What is Inês's apartment like?",
             "option_a": "Grande e luxuoso", "option_b": "Pequeno mas confortável", "option_c": "Grande e confortável", "option_d": "Pequeno e desconfortável",
             "correct_answer": "Pequeno mas confortável"},
            {"question_text": "Which floor is it on?",
             "option_a": "No primeiro andar", "option_b": "No terceiro andar", "option_c": "No segundo andar", "option_d": "No rés-do-chão",
             "correct_answer": "No segundo andar"},
            {"question_text": "How many bedrooms does the apartment have?",
             "option_a": "Um quarto", "option_b": "Três quartos", "option_c": "Dois quartos", "option_d": "Quatro quartos",
             "correct_answer": "Dois quartos"},
            {"question_text": "What is the kitchen like?",
             "option_a": "Velha", "option_b": "Grande", "option_c": "Nova", "option_d": "Pequena",
             "correct_answer": "Nova"},
            {"question_text": "How much rent does Inês pay?",
             "option_a": "Quatrocentos euros", "option_b": "Quinhentos euros", "option_c": "Seiscentos euros", "option_d": "Setecentos euros",
             "correct_answer": "Quinhentos euros"},
        ],
    },
    {
        "title": "O Museu Nacional",
        "topic": "tourism",
        "text": "O Museu Nacional de Arte Antiga fica em Lisboa. Está aberto das dez da manhã às seis da tarde. A entrada custa seis euros para adultos e é gratuita para crianças.",
        "questions": [
            {"question_text": "Where is the museum located?",
             "option_a": "No Porto", "option_b": "Em Coimbra", "option_c": "Em Lisboa", "option_d": "Em Évora",
             "correct_answer": "Em Lisboa"},
            {"question_text": "What time does the museum open?",
             "option_a": "Às nove horas", "option_b": "Às dez horas", "option_c": "Às onze horas", "option_d": "Às oito horas",
             "correct_answer": "Às dez horas"},
            {"question_text": "What time does the museum close?",
             "option_a": "Às cinco da tarde", "option_b": "Às sete da tarde", "option_c": "Às seis da tarde", "option_d": "Às quatro da tarde",
             "correct_answer": "Às seis da tarde"},
            {"question_text": "How much does adult entry cost?",
             "option_a": "Quatro euros", "option_b": "Cinco euros", "option_c": "Oito euros", "option_d": "Seis euros",
             "correct_answer": "Seis euros"},
            {"question_text": "Do children pay to enter?",
             "option_a": "Sim, três euros", "option_b": "Sim, seis euros", "option_c": "Não, é gratuita", "option_d": "Não, se forem menores de três anos",
             "correct_answer": "Não, é gratuita"},
        ],
    },
    {
        "title": "O trabalho do Rui",
        "topic": "work",
        "text": "O Rui é engenheiro e trabalha numa empresa de tecnologia em Lisboa. Começa às nove e acaba às seis. Almoça normalmente na cantina com os colegas.",
        "questions": [
            {"question_text": "What is Rui's profession?",
             "option_a": "Médico", "option_b": "Professor", "option_c": "Engenheiro", "option_d": "Advogado",
             "correct_answer": "Engenheiro"},
            {"question_text": "What type of company does Rui work for?",
             "option_a": "Num banco", "option_b": "Numa empresa de tecnologia", "option_c": "Num hospital", "option_d": "Numa escola",
             "correct_answer": "Numa empresa de tecnologia"},
            {"question_text": "What time does Rui start work?",
             "option_a": "Às oito", "option_b": "Às dez", "option_c": "Às nove", "option_d": "Às nove e meia",
             "correct_answer": "Às nove"},
            {"question_text": "Where does Rui usually have lunch?",
             "option_a": "Em casa", "option_b": "Num restaurante", "option_c": "Na cantina", "option_d": "Num café",
             "correct_answer": "Na cantina"},
            {"question_text": "Who does Rui have lunch with?",
             "option_a": "Sozinho", "option_b": "Com a família", "option_c": "Com os colegas", "option_d": "Com o chefe",
             "correct_answer": "Com os colegas"},
        ],
    },
    {
        "title": "A praia",
        "topic": "leisure",
        "text": "A praia de Cascais fica a trinta quilómetros de Lisboa. No verão há muitos turistas e portugueses. A água é fria mas o sol é muito forte.",
        "questions": [
            {"question_text": "How far is Cascais beach from Lisbon?",
             "option_a": "A cinquenta quilómetros", "option_b": "A vinte quilómetros", "option_c": "A trinta quilómetros", "option_d": "A dez quilómetros",
             "correct_answer": "A trinta quilómetros"},
            {"question_text": "When are there many tourists?",
             "option_a": "No inverno", "option_b": "Na primavera", "option_c": "No outono", "option_d": "No verão",
             "correct_answer": "No verão"},
            {"question_text": "What is the water like?",
             "option_a": "Quente", "option_b": "Morna", "option_c": "Fria", "option_d": "Muito quente",
             "correct_answer": "Fria"},
            {"question_text": "What is the sun like?",
             "option_a": "Fraco", "option_b": "Muito forte", "option_c": "Moderado", "option_d": "Inexistente",
             "correct_answer": "Muito forte"},
            {"question_text": "Who goes to the beach in summer?",
             "option_a": "Só portugueses", "option_b": "Só turistas", "option_c": "Muitos turistas e portugueses", "option_d": "Principalmente crianças",
             "correct_answer": "Muitos turistas e portugueses"},
        ],
    },
    {
        "title": "A língua portuguesa",
        "topic": "language",
        "text": "O português é falado por mais de duzentos e cinquenta milhões de pessoas. É a língua oficial de Portugal, Brasil, e outros países. É uma língua bonita e musical.",
        "questions": [
            {"question_text": "How many people speak Portuguese?",
             "option_a": "Cem milhões", "option_b": "Cento e cinquenta milhões", "option_c": "Mais de duzentos e cinquenta milhões", "option_d": "Duzentos milhões",
             "correct_answer": "Mais de duzentos e cinquenta milhões"},
            {"question_text": "In which European country is Portuguese the official language?",
             "option_a": "Espanha", "option_b": "Portugal", "option_c": "França", "option_d": "Itália",
             "correct_answer": "Portugal"},
            {"question_text": "In which South American country is Portuguese the official language?",
             "option_a": "Argentina", "option_b": "Chile", "option_c": "Brasil", "option_d": "Colômbia",
             "correct_answer": "Brasil"},
            {"question_text": "How does the text describe the Portuguese language?",
             "option_a": "Difícil e complexa", "option_b": "Bonita e musical", "option_c": "Simples e directa", "option_d": "Antiga e rara",
             "correct_answer": "Bonita e musical"},
            {"question_text": "How many countries speak Portuguese?",
             "option_a": "Só em Portugal", "option_b": "Portugal e Brasil apenas", "option_c": "Portugal, Brasil e outros países", "option_d": "Em toda a Europa",
             "correct_answer": "Portugal, Brasil e outros países"},
        ],
    },
    {
        "title": "A padaria",
        "topic": "daily_life",
        "text": "Todos os dias de manhã, a D. Rosa vai à padaria comprar pão. A padaria abre às sete horas. O pão custa sessenta cêntimos.",
        "questions": [
            {"question_text": "When does D. Rosa go to the bakery?",
             "option_a": "Ao fim da tarde", "option_b": "Ao almoço", "option_c": "Todos os dias de manhã", "option_d": "Uma vez por semana",
             "correct_answer": "Todos os dias de manhã"},
            {"question_text": "What does D. Rosa go to buy?",
             "option_a": "Leite", "option_b": "Bolo", "option_c": "Pão", "option_d": "Café",
             "correct_answer": "Pão"},
            {"question_text": "What time does the bakery open?",
             "option_a": "Às seis horas", "option_b": "Às oito horas", "option_c": "Às sete horas", "option_d": "Às sete e meia",
             "correct_answer": "Às sete horas"},
            {"question_text": "How much does the bread cost?",
             "option_a": "Cinquenta cêntimos", "option_b": "Sessenta cêntimos", "option_c": "Setenta cêntimos", "option_d": "Um euro",
             "correct_answer": "Sessenta cêntimos"},
            {"question_text": "How often does D. Rosa go to the bakery?",
             "option_a": "Uma vez por semana", "option_b": "Ao fim de semana", "option_c": "Todos os dias", "option_d": "Duas vezes por semana",
             "correct_answer": "Todos os dias"},
        ],
    },
    {
        "title": "Lisboa capital",
        "topic": "geography",
        "text": "Lisboa é a capital de Portugal e fica no sudoeste da Europa. Tem cerca de meio milhão de habitantes na cidade. É conhecida pelos seus miradouros, pastéis de nata e o fado.",
        "questions": [
            {"question_text": "What is the capital of Portugal?",
             "option_a": "Porto", "option_b": "Coimbra", "option_c": "Braga", "option_d": "Lisboa",
             "correct_answer": "Lisboa"},
            {"question_text": "Where is Lisbon in Europe?",
             "option_a": "No nordeste", "option_b": "No sudoeste", "option_c": "No centro", "option_d": "No norte",
             "correct_answer": "No sudoeste"},
            {"question_text": "What is the population of Lisbon?",
             "option_a": "Um milhão", "option_b": "Dois milhões", "option_c": "Cerca de meio milhão", "option_d": "Trezentos mil",
             "correct_answer": "Cerca de meio milhão"},
            {"question_text": "What is Lisbon known for?",
             "option_a": "As fontes, os jardins e o futebol", "option_b": "Os miradouros, pastéis de nata e o fado", "option_c": "Os museus, as praias e o surf", "option_d": "Os castelos, as pontes e o vinho",
             "correct_answer": "Os miradouros, pastéis de nata e o fado"},
            {"question_text": "What type of attraction is fado?",
             "option_a": "Uma dança", "option_b": "Uma comida", "option_c": "Algo característico de Lisboa", "option_d": "Um festival",
             "correct_answer": "Algo característico de Lisboa"},
        ],
    },
    {
        "title": "Uma visita ao Porto",
        "topic": "tourism",
        "text": "O Marco foi ao Porto visitar os amigos durante o fim de semana. Visitou a ribeira, provou vinho do Porto e passeou pela cidade velha. Ficou num hostel no centro.",
        "questions": [
            {"question_text": "Why did Marco go to Porto?",
             "option_a": "A trabalho", "option_b": "Visitar amigos", "option_c": "A um congresso", "option_d": "Estudar",
             "correct_answer": "Visitar amigos"},
            {"question_text": "When did Marco visit Porto?",
             "option_a": "Durante a semana", "option_b": "No fim de semana", "option_c": "Nas férias de verão", "option_d": "No Natal",
             "correct_answer": "No fim de semana"},
            {"question_text": "What did Marco try?",
             "option_a": "Francesinha", "option_b": "Bacalhau", "option_c": "Vinho do Porto", "option_d": "Caldo verde",
             "correct_answer": "Vinho do Porto"},
            {"question_text": "What did Marco visit?",
             "option_a": "O museu e os jardins", "option_b": "A ribeira e a cidade velha", "option_c": "O estádio e a universidade", "option_d": "As praias e os parques",
             "correct_answer": "A ribeira e a cidade velha"},
            {"question_text": "Where did Marco stay?",
             "option_a": "Num hotel de luxo", "option_b": "Em casa dos amigos", "option_c": "Num hostel no centro", "option_d": "Num apartamento",
             "correct_answer": "Num hostel no centro"},
        ],
    },
    {
        "title": "O Natal em família",
        "topic": "culture",
        "text": "Em Portugal, o Natal celebra-se a vinte e cinco de dezembro. As famílias juntam-se para comer bacalhau no dia vinte e quatro à noite. As crianças recebem prendas.",
        "questions": [
            {"question_text": "When is Christmas celebrated in Portugal?",
             "option_a": "A vinte e quatro de dezembro", "option_b": "A vinte e cinco de dezembro", "option_c": "A um de janeiro", "option_d": "A seis de janeiro",
             "correct_answer": "A vinte e cinco de dezembro"},
            {"question_text": "When do families get together?",
             "option_a": "No dia vinte e cinco de manhã", "option_b": "No dia vinte e quatro à noite", "option_c": "No dia vinte e três", "option_d": "A qualquer momento",
             "correct_answer": "No dia vinte e quatro à noite"},
            {"question_text": "What do families eat on the 24th?",
             "option_a": "Peru", "option_b": "Frango assado", "option_c": "Bacalhau", "option_d": "Leitão",
             "correct_answer": "Bacalhau"},
            {"question_text": "Who receives gifts?",
             "option_a": "Os adultos", "option_b": "Os idosos", "option_c": "Toda a família", "option_d": "As crianças",
             "correct_answer": "As crianças"},
            {"question_text": "Which country do these traditions belong to?",
             "option_a": "Brasil", "option_b": "Espanha", "option_c": "Portugal", "option_d": "França",
             "correct_answer": "Portugal"},
        ],
    },
    {
        "title": "No banco",
        "topic": "finance",
        "text": "A Luísa vai ao banco para abrir uma conta. Fala com o funcionário e preenche um formulário. Recebe o cartão em três dias úteis.",
        "questions": [
            {"question_text": "Where does Luísa go?",
             "option_a": "À farmácia", "option_b": "Ao correio", "option_c": "Ao banco", "option_d": "À câmara",
             "correct_answer": "Ao banco"},
            {"question_text": "Why does she go there?",
             "option_a": "Levantar dinheiro", "option_b": "Abrir uma conta", "option_c": "Pedir um empréstimo", "option_d": "Mudar divisas",
             "correct_answer": "Abrir uma conta"},
            {"question_text": "Who does Luísa speak to?",
             "option_a": "Com o director", "option_b": "Com o gerente", "option_c": "Com o funcionário", "option_d": "Com um colega",
             "correct_answer": "Com o funcionário"},
            {"question_text": "What does Luísa fill in?",
             "option_a": "Um contrato", "option_b": "Um formulário", "option_c": "Um cheque", "option_d": "Uma carta",
             "correct_answer": "Um formulário"},
            {"question_text": "When does she receive her card?",
             "option_a": "No mesmo dia", "option_b": "Em uma semana", "option_c": "Em três dias úteis", "option_d": "Em dois dias",
             "correct_answer": "Em três dias úteis"},
        ],
    },
    {
        "title": "O jardim público",
        "topic": "leisure",
        "text": "O jardim do Parque Eduardo VII fica no centro de Lisboa. É um lugar tranquilo para passear e descansar. Há muitas flores e árvores bonitas.",
        "questions": [
            {"question_text": "What is the name of the park?",
             "option_a": "Parque das Nações", "option_b": "Parque Eduardo VII", "option_c": "Jardim Botânico", "option_d": "Tapada de Mafra",
             "correct_answer": "Parque Eduardo VII"},
            {"question_text": "Where is the park?",
             "option_a": "No Porto", "option_b": "No centro de Lisboa", "option_c": "Em Sintra", "option_d": "Em Cascais",
             "correct_answer": "No centro de Lisboa"},
            {"question_text": "How is the park described?",
             "option_a": "Barulhento e movimentado", "option_b": "Tranquilo", "option_c": "Pequeno e sem sombra", "option_d": "Muito moderno",
             "correct_answer": "Tranquilo"},
            {"question_text": "What is the park used for?",
             "option_a": "Para fazer desporto", "option_b": "Para estudar", "option_c": "Para passear e descansar", "option_d": "Para festas",
             "correct_answer": "Para passear e descansar"},
            {"question_text": "What can be found in the park?",
             "option_a": "Um lago e patos", "option_b": "Flores e árvores bonitas", "option_c": "Bares e restaurantes", "option_d": "Uma pista de skate",
             "correct_answer": "Flores e árvores bonitas"},
        ],
    },
    {
        "title": "O correio",
        "topic": "services",
        "text": "A Carolina vai ao correio enviar uma encomenda para a sua irmã no Brasil. A encomenda pesa dois quilos. A funcionária diz que chega em cinco a dez dias úteis.",
        "questions": [
            {"question_text": "Where does Carolina go?",
             "option_a": "Ao banco", "option_b": "À farmácia", "option_c": "Ao correio", "option_d": "À loja",
             "correct_answer": "Ao correio"},
            {"question_text": "What does Carolina want to send?",
             "option_a": "Uma carta", "option_b": "Uma encomenda", "option_c": "Um embrulho pequeno", "option_d": "Dinheiro",
             "correct_answer": "Uma encomenda"},
            {"question_text": "Where is the package going?",
             "option_a": "Para o Porto", "option_b": "Para Espanha", "option_c": "Para o Brasil", "option_d": "Para França",
             "correct_answer": "Para o Brasil"},
            {"question_text": "How much does the package weigh?",
             "option_a": "Um quilo", "option_b": "Três quilos", "option_c": "Dois quilos", "option_d": "Cinco quilos",
             "correct_answer": "Dois quilos"},
            {"question_text": "How long will the package take to arrive?",
             "option_a": "Em dois a três dias", "option_b": "Em cinco a dez dias úteis", "option_c": "Em um mês", "option_d": "Em três semanas",
             "correct_answer": "Em cinco a dez dias úteis"},
        ],
    },
    {
        "title": "O transporte público",
        "topic": "transport",
        "text": "Em Lisboa há metro, autocarros e eléctricos. O metro é rápido e chega a muitas partes da cidade. O bilhete custa um euro e cinquenta.",
        "questions": [
            {"question_text": "What forms of public transport exist in Lisbon?",
             "option_a": "Só o metro e os táxis", "option_b": "Metro, autocarros e eléctricos", "option_c": "Comboios e autocarros", "option_d": "Metro, comboios e barcos",
             "correct_answer": "Metro, autocarros e eléctricos"},
            {"question_text": "What is the metro like?",
             "option_a": "Lento e pouco conveniente", "option_b": "Rápido", "option_c": "Caro e eficiente", "option_d": "Moderno mas lento",
             "correct_answer": "Rápido"},
            {"question_text": "Which parts of the city does the metro reach?",
             "option_a": "Só ao centro", "option_b": "Só ao aeroporto", "option_c": "A muitas partes da cidade", "option_d": "Só às zonas turísticas",
             "correct_answer": "A muitas partes da cidade"},
            {"question_text": "How much does a metro ticket cost?",
             "option_a": "Um euro", "option_b": "Dois euros", "option_c": "Um euro e cinquenta", "option_d": "Dois euros e cinquenta",
             "correct_answer": "Um euro e cinquenta"},
            {"question_text": "Which city does the text describe?",
             "option_a": "Porto", "option_b": "Coimbra", "option_c": "Braga", "option_d": "Lisboa",
             "correct_answer": "Lisboa"},
        ],
    },
    {
        "title": "Uma carta de apresentação",
        "topic": "personal_info",
        "text": "Chamo-me Beatriz Silva. Tenho vinte e dois anos e sou de Braga. Sou estudante de medicina no Porto. Falo português, inglês e um pouco de espanhol.",
        "questions": [
            {"question_text": "What is the person's name?",
             "option_a": "Ana Silva", "option_b": "Beatriz Costa", "option_c": "Beatriz Silva", "option_d": "Maria Silva",
             "correct_answer": "Beatriz Silva"},
            {"question_text": "How old is she?",
             "option_a": "Vinte anos", "option_b": "Vinte e um anos", "option_c": "Vinte e dois anos", "option_d": "Vinte e três anos",
             "correct_answer": "Vinte e dois anos"},
            {"question_text": "Where is she from?",
             "option_a": "Do Porto", "option_b": "De Lisboa", "option_c": "De Braga", "option_d": "De Coimbra",
             "correct_answer": "De Braga"},
            {"question_text": "What does she study?",
             "option_a": "Direito", "option_b": "Medicina", "option_c": "Engenharia", "option_d": "Letras",
             "correct_answer": "Medicina"},
            {"question_text": "What languages does she speak?",
             "option_a": "Português e inglês", "option_b": "Português, inglês e francês", "option_c": "Português, inglês e um pouco de espanhol", "option_d": "Três línguas fluentemente",
             "correct_answer": "Português, inglês e um pouco de espanhol"},
        ],
    },
    {
        "title": "O fado",
        "topic": "culture",
        "text": "O fado é a música tradicional de Portugal. Nasceu em Lisboa no século dezanove. É conhecido pela sua melancolia e é Património da Humanidade da UNESCO.",
        "questions": [
            {"question_text": "What is fado?",
             "option_a": "Uma dança tradicional", "option_b": "A música tradicional de Portugal", "option_c": "Um festival de verão", "option_d": "Um instrumento musical",
             "correct_answer": "A música tradicional de Portugal"},
            {"question_text": "Where did fado originate?",
             "option_a": "No Porto", "option_b": "Em Coimbra", "option_c": "Em Lisboa", "option_d": "Em Évora",
             "correct_answer": "Em Lisboa"},
            {"question_text": "In which century did fado originate?",
             "option_a": "No século dezoito", "option_b": "No século dezanove", "option_c": "No século vinte", "option_d": "No século dezassete",
             "correct_answer": "No século dezanove"},
            {"question_text": "What characteristic is fado known for?",
             "option_a": "Pela alegria e energia", "option_b": "Pelo ritmo rápido", "option_c": "Pela melancolia", "option_d": "Pelas letras engraçadas",
             "correct_answer": "Pela melancolia"},
            {"question_text": "What UNESCO title does fado hold?",
             "option_a": "Tesouro Nacional", "option_b": "Património da Humanidade", "option_c": "Cultura Imaterial", "option_d": "Arte Universal",
             "correct_answer": "Património da Humanidade"},
        ],
    },
]
