"""
600 most-common European Portuguese (pt-PT) A1 words.
Each entry: (id, word, translation, category)
Category values: 'verb' | 'noun' | 'adjective' | 'adverb' | 'phrase' | 'number' | 'pronoun' | 'preposition'
"""

WORDS: list[tuple[int, str, str, str]] = [
    # ── Greetings & Phrases ──────────────────────────────────────────────
    (1,  "olá",               "hello",                      "phrase"),
    (2,  "bom dia",           "good morning",               "phrase"),
    (3,  "boa tarde",         "good afternoon",             "phrase"),
    (4,  "boa noite",         "good evening / good night",  "phrase"),
    (5,  "obrigado",          "thank you (m.)",             "phrase"),
    (6,  "obrigada",          "thank you (f.)",             "phrase"),
    (7,  "de nada",           "you're welcome",             "phrase"),
    (8,  "por favor",         "please",                     "phrase"),
    (9,  "desculpe",          "excuse me / sorry",          "phrase"),
    (10, "com licença",       "excuse me (to pass)",        "phrase"),
    (11, "sim",               "yes",                        "phrase"),
    (12, "não",               "no",                         "phrase"),
    (13, "talvez",            "maybe",                      "adverb"),
    (14, "até logo",          "see you soon",               "phrase"),
    (15, "até amanhã",        "see you tomorrow",           "phrase"),
    (16, "tchau",             "bye",                        "phrase"),
    (17, "como está?",        "how are you? (formal)",      "phrase"),
    (18, "como estás?",       "how are you? (informal)",    "phrase"),
    (19, "estou bem",         "I am fine",                  "phrase"),
    (20, "muito prazer",      "nice to meet you",           "phrase"),

    # ── Pronouns ─────────────────────────────────────────────────────────
    (21, "eu",                "I",                          "pronoun"),
    (22, "tu",                "you (informal)",             "pronoun"),
    (23, "ele",               "he",                         "pronoun"),
    (24, "ela",               "she",                        "pronoun"),
    (25, "nós",               "we",                         "pronoun"),
    (26, "vocês",             "you (plural)",               "pronoun"),
    (27, "eles",              "they (m.)",                  "pronoun"),
    (28, "elas",              "they (f.)",                  "pronoun"),
    (29, "você",              "you (formal)",               "pronoun"),
    (30, "me",                "me / to me",                 "pronoun"),

    # ── High-frequency verbs ─────────────────────────────────────────────
    (31, "ser",               "to be (permanent)",          "verb"),
    (32, "estar",             "to be (temporary)",          "verb"),
    (33, "ter",               "to have",                    "verb"),
    (34, "ir",                "to go",                      "verb"),
    (35, "fazer",             "to do / to make",            "verb"),
    (36, "poder",             "to be able to / can",        "verb"),
    (37, "querer",            "to want",                    "verb"),
    (38, "saber",             "to know (fact)",             "verb"),
    (39, "ver",               "to see",                     "verb"),
    (40, "vir",               "to come",                    "verb"),
    (41, "dar",               "to give",                    "verb"),
    (42, "dizer",             "to say / to tell",           "verb"),
    (43, "ficar",             "to stay / to become",        "verb"),
    (44, "gostar",            "to like",                    "verb"),
    (45, "precisar",          "to need",                    "verb"),
    (46, "falar",             "to speak / to talk",         "verb"),
    (47, "trabalhar",         "to work",                    "verb"),
    (48, "morar",             "to live (reside)",           "verb"),
    (49, "estudar",           "to study",                   "verb"),
    (50, "comer",             "to eat",                     "verb"),
    (51, "beber",             "to drink",                   "verb"),
    (52, "comprar",           "to buy",                     "verb"),
    (53, "vender",            "to sell",                    "verb"),
    (54, "abrir",             "to open",                    "verb"),
    (55, "fechar",            "to close",                   "verb"),
    (56, "entrar",            "to enter",                   "verb"),
    (57, "sair",              "to leave / to go out",       "verb"),
    (58, "chegar",            "to arrive",                  "verb"),
    (59, "partir",            "to depart / to leave",       "verb"),
    (60, "voltar",            "to return",                  "verb"),
    (61, "esperar",           "to wait / to hope",          "verb"),
    (62, "chamar",            "to call / to be named",      "verb"),
    (63, "ajudar",            "to help",                    "verb"),
    (64, "pagar",             "to pay",                     "verb"),
    (65, "levar",             "to take / to carry",         "verb"),
    (66, "trazer",            "to bring",                   "verb"),
    (67, "ouvir",             "to hear / to listen",        "verb"),
    (68, "ler",               "to read",                    "verb"),
    (69, "escrever",          "to write",                   "verb"),
    (70, "perguntar",         "to ask (a question)",        "verb"),
    (71, "responder",         "to answer",                  "verb"),
    (72, "perceber",          "to understand / to notice",  "verb"),
    (73, "começar",           "to begin / to start",        "verb"),
    (74, "acabar",            "to finish / to end",         "verb"),
    (75, "seguir",            "to follow / to continue",    "verb"),
    (76, "encontrar",         "to find / to meet",          "verb"),
    (77, "lembrar",           "to remember",                "verb"),
    (78, "esquecer",          "to forget",                  "verb"),
    (79, "dormir",            "to sleep",                   "verb"),
    (80, "acordar",           "to wake up",                 "verb"),
    (81, "sentar",            "to sit",                     "verb"),
    (82, "andar",             "to walk / to go",            "verb"),
    (83, "correr",            "to run",                     "verb"),
    (84, "nadar",             "to swim",                    "verb"),
    (85, "jogar",             "to play (sport/game)",       "verb"),
    (86, "tocar",             "to touch / to play (music)", "verb"),
    (87, "cozinhar",          "to cook",                    "verb"),
    (88, "limpar",            "to clean",                   "verb"),
    (89, "lavar",             "to wash",                    "verb"),
    (90, "usar",              "to use",                     "verb"),

    # ── Numbers ───────────────────────────────────────────────────────────
    (91,  "zero",             "zero",                       "number"),
    (92,  "um",               "one",                        "number"),
    (93,  "dois",             "two",                        "number"),
    (94,  "três",             "three",                      "number"),
    (95,  "quatro",           "four",                       "number"),
    (96,  "cinco",            "five",                       "number"),
    (97,  "seis",             "six",                        "number"),
    (98,  "sete",             "seven",                      "number"),
    (99,  "oito",             "eight",                      "number"),
    (100, "nove",             "nine",                       "number"),
    (101, "dez",              "ten",                        "number"),
    (102, "onze",             "eleven",                     "number"),
    (103, "doze",             "twelve",                     "number"),
    (104, "treze",            "thirteen",                   "number"),
    (105, "catorze",          "fourteen",                   "number"),
    (106, "quinze",           "fifteen",                    "number"),
    (107, "dezasseis",        "sixteen",                    "number"),
    (108, "dezassete",        "seventeen",                  "number"),
    (109, "dezoito",          "eighteen",                   "number"),
    (110, "dezanove",         "nineteen",                   "number"),
    (111, "vinte",            "twenty",                     "number"),
    (112, "trinta",           "thirty",                     "number"),
    (113, "quarenta",         "forty",                      "number"),
    (114, "cinquenta",        "fifty",                      "number"),
    (115, "sessenta",         "sixty",                      "number"),
    (116, "setenta",          "seventy",                    "number"),
    (117, "oitenta",          "eighty",                     "number"),
    (118, "noventa",          "ninety",                     "number"),
    (119, "cem",              "one hundred",                "number"),
    (120, "mil",              "one thousand",               "number"),

    # ── Days & Time ───────────────────────────────────────────────────────
    (121, "segunda-feira",    "Monday",                     "noun"),
    (122, "terça-feira",      "Tuesday",                    "noun"),
    (123, "quarta-feira",     "Wednesday",                  "noun"),
    (124, "quinta-feira",     "Thursday",                   "noun"),
    (125, "sexta-feira",      "Friday",                     "noun"),
    (126, "sábado",           "Saturday",                   "noun"),
    (127, "domingo",          "Sunday",                     "noun"),
    (128, "hoje",             "today",                      "adverb"),
    (129, "amanhã",           "tomorrow",                   "adverb"),
    (130, "ontem",            "yesterday",                  "adverb"),
    (131, "agora",            "now",                        "adverb"),
    (132, "depois",           "after / later",              "adverb"),
    (133, "antes",            "before",                     "adverb"),
    (134, "sempre",           "always",                     "adverb"),
    (135, "nunca",            "never",                      "adverb"),
    (136, "às vezes",         "sometimes",                  "adverb"),
    (137, "hora",             "hour / time",                "noun"),
    (138, "minuto",           "minute",                     "noun"),
    (139, "dia",              "day",                        "noun"),
    (140, "semana",           "week",                       "noun"),
    (141, "mês",              "month",                      "noun"),
    (142, "ano",              "year",                       "noun"),
    (143, "manhã",            "morning",                    "noun"),
    (144, "tarde",            "afternoon / evening",        "noun"),
    (145, "noite",            "night",                      "noun"),

    # ── Months ────────────────────────────────────────────────────────────
    (146, "janeiro",          "January",                    "noun"),
    (147, "fevereiro",        "February",                   "noun"),
    (148, "março",            "March",                      "noun"),
    (149, "abril",            "April",                      "noun"),
    (150, "maio",             "May",                        "noun"),
    (151, "junho",            "June",                       "noun"),
    (152, "julho",            "July",                       "noun"),
    (153, "agosto",           "August",                     "noun"),
    (154, "setembro",         "September",                  "noun"),
    (155, "outubro",          "October",                    "noun"),
    (156, "novembro",         "November",                   "noun"),
    (157, "dezembro",         "December",                   "noun"),

    # ── Family ────────────────────────────────────────────────────────────
    (158, "família",          "family",                     "noun"),
    (159, "mãe",              "mother",                     "noun"),
    (160, "pai",              "father",                     "noun"),
    (161, "filho",            "son",                        "noun"),
    (162, "filha",            "daughter",                   "noun"),
    (163, "irmão",            "brother",                    "noun"),
    (164, "irmã",             "sister",                     "noun"),
    (165, "avô",              "grandfather",                "noun"),
    (166, "avó",              "grandmother",                "noun"),
    (167, "tio",              "uncle",                      "noun"),
    (168, "tia",              "aunt",                       "noun"),
    (169, "primo",            "cousin (m.)",                "noun"),
    (170, "prima",            "cousin (f.)",                "noun"),
    (171, "marido",           "husband",                    "noun"),
    (172, "esposa",           "wife",                       "noun"),
    (173, "namorado",         "boyfriend",                  "noun"),
    (174, "namorada",         "girlfriend",                 "noun"),
    (175, "amigo",            "friend (m.)",                "noun"),
    (176, "amiga",            "friend (f.)",                "noun"),
    (177, "pessoa",           "person",                     "noun"),
    (178, "homem",            "man",                        "noun"),
    (179, "mulher",           "woman",                      "noun"),
    (180, "criança",          "child",                      "noun"),

    # ── Body ──────────────────────────────────────────────────────────────
    (181, "cabeça",           "head",                       "noun"),
    (182, "olho",             "eye",                        "noun"),
    (183, "nariz",            "nose",                       "noun"),
    (184, "boca",             "mouth",                      "noun"),
    (185, "orelha",           "ear",                        "noun"),
    (186, "cabelo",           "hair",                       "noun"),
    (187, "mão",              "hand",                       "noun"),
    (188, "braço",            "arm",                        "noun"),
    (189, "perna",            "leg",                        "noun"),
    (190, "pé",               "foot",                       "noun"),
    (191, "coração",          "heart",                      "noun"),
    (192, "corpo",            "body",                       "noun"),
    (193, "dente",            "tooth",                      "noun"),
    (194, "costas",           "back",                       "noun"),
    (195, "barriga",          "belly / stomach",            "noun"),

    # ── Home ──────────────────────────────────────────────────────────────
    (196, "casa",             "house / home",               "noun"),
    (197, "apartamento",      "apartment",                  "noun"),
    (198, "quarto",           "bedroom / room",             "noun"),
    (199, "sala",             "living room",                "noun"),
    (200, "cozinha",          "kitchen",                    "noun"),
    (201, "casa de banho",    "bathroom",                   "noun"),
    (202, "jardim",           "garden",                     "noun"),
    (203, "porta",            "door",                       "noun"),
    (204, "janela",           "window",                     "noun"),
    (205, "mesa",             "table",                      "noun"),
    (206, "cadeira",          "chair",                      "noun"),
    (207, "cama",             "bed",                        "noun"),
    (208, "sofá",             "sofa / couch",               "noun"),
    (209, "armário",          "wardrobe / cupboard",        "noun"),
    (210, "chão",             "floor / ground",             "noun"),
    (211, "tecto",            "ceiling",                    "noun"),
    (212, "parede",           "wall",                       "noun"),
    (213, "escada",           "stairs",                     "noun"),
    (214, "chave",            "key",                        "noun"),
    (215, "luz",              "light",                      "noun"),

    # ── Food & Drink ──────────────────────────────────────────────────────
    (216, "água",             "water",                      "noun"),
    (217, "café",             "coffee",                     "noun"),
    (218, "leite",            "milk",                       "noun"),
    (219, "sumo",             "juice",                      "noun"),
    (220, "vinho",            "wine",                       "noun"),
    (221, "cerveja",          "beer",                       "noun"),
    (222, "pão",              "bread",                      "noun"),
    (223, "arroz",            "rice",                       "noun"),
    (224, "massa",            "pasta",                      "noun"),
    (225, "carne",            "meat",                       "noun"),
    (226, "peixe",            "fish",                       "noun"),
    (227, "frango",           "chicken",                    "noun"),
    (228, "bacalhau",         "codfish",                    "noun"),
    (229, "ovo",              "egg",                        "noun"),
    (230, "queijo",           "cheese",                     "noun"),
    (231, "manteiga",         "butter",                     "noun"),
    (232, "açúcar",           "sugar",                      "noun"),
    (233, "sal",              "salt",                       "noun"),
    (234, "azeite",           "olive oil",                  "noun"),
    (235, "sopa",             "soup",                       "noun"),
    (236, "salada",           "salad",                      "noun"),
    (237, "fruta",            "fruit",                      "noun"),
    (238, "maçã",             "apple",                      "noun"),
    (239, "laranja",          "orange",                     "noun"),
    (240, "banana",           "banana",                     "noun"),
    (241, "tomate",           "tomato",                     "noun"),
    (242, "alface",           "lettuce",                    "noun"),
    (243, "cebola",           "onion",                      "noun"),
    (244, "alho",             "garlic",                     "noun"),
    (245, "batata",           "potato",                     "noun"),
    (246, "cenoura",          "carrot",                     "noun"),
    (247, "sobremesa",        "dessert",                    "noun"),
    (248, "bolo",             "cake",                       "noun"),
    (249, "gelado",           "ice cream",                  "noun"),
    (250, "refeição",         "meal",                       "noun"),

    # ── City & Transport ──────────────────────────────────────────────────
    (251, "cidade",           "city",                       "noun"),
    (252, "rua",              "street",                     "noun"),
    (253, "avenida",          "avenue",                     "noun"),
    (254, "praça",            "square / plaza",             "noun"),
    (255, "parque",           "park",                       "noun"),
    (256, "hospital",         "hospital",                   "noun"),
    (257, "farmácia",         "pharmacy",                   "noun"),
    (258, "banco",            "bank",                       "noun"),
    (259, "supermercado",     "supermarket",                "noun"),
    (260, "loja",             "shop / store",               "noun"),
    (261, "mercado",          "market",                     "noun"),
    (262, "restaurante",      "restaurant",                 "noun"),
    (263, "café",             "café / coffee shop",         "noun"),
    (264, "escola",           "school",                     "noun"),
    (265, "universidade",     "university",                 "noun"),
    (266, "escritório",       "office",                     "noun"),
    (267, "hotel",            "hotel",                      "noun"),
    (268, "estação",          "station",                    "noun"),
    (269, "aeroporto",        "airport",                    "noun"),
    (270, "praia",            "beach",                      "noun"),
    (271, "comboio",          "train",                      "noun"),
    (272, "autocarro",        "bus",                        "noun"),
    (273, "metro",            "metro / subway",             "noun"),
    (274, "táxi",             "taxi",                       "noun"),
    (275, "carro",            "car",                        "noun"),
    (276, "bicicleta",        "bicycle",                    "noun"),
    (277, "avião",            "aeroplane",                  "noun"),
    (278, "barco",            "boat",                       "noun"),
    (279, "paragem",          "bus stop",                   "noun"),
    (280, "bilhete",          "ticket",                     "noun"),

    # ── Colours ───────────────────────────────────────────────────────────
    (281, "branco",           "white",                      "adjective"),
    (282, "preto",            "black",                      "adjective"),
    (283, "cinzento",         "grey",                       "adjective"),
    (284, "vermelho",         "red",                        "adjective"),
    (285, "azul",             "blue",                       "adjective"),
    (286, "verde",            "green",                      "adjective"),
    (287, "amarelo",          "yellow",                     "adjective"),
    (288, "laranja",          "orange (colour)",            "adjective"),
    (289, "rosa",             "pink",                       "adjective"),
    (290, "roxo",             "purple",                     "adjective"),
    (291, "castanho",         "brown",                      "adjective"),
    (292, "cor de laranja",   "orange (colour)",            "adjective"),

    # ── Common adjectives ─────────────────────────────────────────────────
    (293, "bom",              "good",                       "adjective"),
    (294, "mau",              "bad",                        "adjective"),
    (295, "grande",           "big / large",                "adjective"),
    (296, "pequeno",          "small / little",             "adjective"),
    (297, "novo",             "new / young",                "adjective"),
    (298, "velho",            "old",                        "adjective"),
    (299, "bonito",           "beautiful / nice",           "adjective"),
    (300, "feio",             "ugly",                       "adjective"),
    (301, "rápido",           "fast",                       "adjective"),
    (302, "lento",            "slow",                       "adjective"),
    (303, "fácil",            "easy",                       "adjective"),
    (304, "difícil",          "difficult",                  "adjective"),
    (305, "caro",             "expensive",                  "adjective"),
    (306, "barato",           "cheap",                      "adjective"),
    (307, "quente",           "hot / warm",                 "adjective"),
    (308, "frio",             "cold",                       "adjective"),
    (309, "alto",             "tall / high",                "adjective"),
    (310, "baixo",            "short / low",                "adjective"),
    (311, "gordo",            "fat",                        "adjective"),
    (312, "magro",            "thin / slim",                "adjective"),
    (313, "forte",            "strong",                     "adjective"),
    (314, "fraco",            "weak",                       "adjective"),
    (315, "feliz",            "happy",                      "adjective"),
    (316, "triste",           "sad",                        "adjective"),
    (317, "cansado",          "tired",                      "adjective"),
    (318, "doente",           "sick / ill",                 "adjective"),
    (319, "saudável",         "healthy",                    "adjective"),
    (320, "limpo",            "clean",                      "adjective"),
    (321, "sujo",             "dirty",                      "adjective"),
    (322, "aberto",           "open",                       "adjective"),
    (323, "fechado",          "closed",                     "adjective"),
    (324, "livre",            "free / available",           "adjective"),
    (325, "ocupado",          "busy / occupied",            "adjective"),
    (326, "certo",            "correct / right",            "adjective"),
    (327, "errado",           "wrong / incorrect",          "adjective"),
    (328, "cheio",            "full",                       "adjective"),
    (329, "vazio",            "empty",                      "adjective"),
    (330, "simples",          "simple",                     "adjective"),

    # ── Prepositions & Conjunctions ───────────────────────────────────────
    (331, "em",               "in / at / on",               "preposition"),
    (332, "de",               "of / from",                  "preposition"),
    (333, "para",             "for / to",                   "preposition"),
    (334, "com",              "with",                       "preposition"),
    (335, "sem",              "without",                    "preposition"),
    (336, "por",              "by / through / for",         "preposition"),
    (337, "entre",            "between / among",            "preposition"),
    (338, "sobre",            "on top of / about",          "preposition"),
    (339, "até",              "until / up to",              "preposition"),
    (340, "desde",            "since / from",               "preposition"),
    (341, "depois de",        "after",                      "preposition"),
    (342, "antes de",         "before",                     "preposition"),
    (343, "perto de",         "near / close to",            "preposition"),
    (344, "longe de",         "far from",                   "preposition"),
    (345, "à frente de",      "in front of",                "preposition"),
    (346, "atrás de",         "behind",                     "preposition"),
    (347, "ao lado de",       "next to",                    "preposition"),
    (348, "dentro de",        "inside",                     "preposition"),
    (349, "fora de",          "outside",                    "preposition"),
    (350, "e",                "and",                        "preposition"),
    (351, "ou",               "or",                         "preposition"),
    (352, "mas",              "but",                        "preposition"),
    (353, "porque",           "because",                    "preposition"),
    (354, "que",              "that / which",               "preposition"),
    (355, "se",               "if",                         "preposition"),

    # ── Question words ────────────────────────────────────────────────────
    (356, "o que",            "what",                       "phrase"),
    (357, "quem",             "who",                        "phrase"),
    (358, "onde",             "where",                      "phrase"),
    (359, "quando",           "when",                       "phrase"),
    (360, "como",             "how",                        "phrase"),
    (361, "porque",           "why",                        "phrase"),
    (362, "quanto",           "how much",                   "phrase"),
    (363, "quantos",          "how many",                   "phrase"),
    (364, "qual",             "which",                      "phrase"),

    # ── Nature & Weather ──────────────────────────────────────────────────
    (365, "tempo",            "weather / time",             "noun"),
    (366, "sol",              "sun",                        "noun"),
    (367, "chuva",            "rain",                       "noun"),
    (368, "vento",            "wind",                       "noun"),
    (369, "neve",             "snow",                       "noun"),
    (370, "nuvem",            "cloud",                      "noun"),
    (371, "frio",             "cold (noun)",                "noun"),
    (372, "calor",            "heat / warmth",              "noun"),
    (373, "mar",              "sea",                        "noun"),
    (374, "rio",              "river",                      "noun"),
    (375, "montanha",         "mountain",                   "noun"),
    (376, "floresta",         "forest",                     "noun"),
    (377, "campo",            "field / countryside",        "noun"),
    (378, "ilha",             "island",                     "noun"),
    (379, "flor",             "flower",                     "noun"),
    (380, "árvore",           "tree",                       "noun"),

    # ── Clothes ───────────────────────────────────────────────────────────
    (381, "roupa",            "clothes / clothing",         "noun"),
    (382, "camisa",           "shirt",                      "noun"),
    (383, "camisola",         "sweater / jumper",           "noun"),
    (384, "calças",           "trousers / pants",           "noun"),
    (385, "saia",             "skirt",                      "noun"),
    (386, "vestido",          "dress",                      "noun"),
    (387, "casaco",           "coat / jacket",              "noun"),
    (388, "sapatos",          "shoes",                      "noun"),
    (389, "meias",            "socks",                      "noun"),
    (390, "chapéu",           "hat",                        "noun"),
    (391, "mala",             "bag / suitcase",             "noun"),
    (392, "bolso",            "pocket",                     "noun"),

    # ── Work & Education ──────────────────────────────────────────────────
    (393, "trabalho",         "work / job",                 "noun"),
    (394, "emprego",          "employment / job",           "noun"),
    (395, "empresa",          "company / firm",             "noun"),
    (396, "chefe",            "boss / chief",               "noun"),
    (397, "colega",           "colleague",                  "noun"),
    (398, "reunião",          "meeting",                    "noun"),
    (399, "livro",            "book",                       "noun"),
    (400, "caderno",          "notebook",                   "noun"),
    (401, "caneta",           "pen",                        "noun"),
    (402, "lápis",            "pencil",                     "noun"),
    (403, "papel",            "paper",                      "noun"),
    (404, "computador",       "computer",                   "noun"),
    (405, "telemóvel",        "mobile phone",               "noun"),
    (406, "internet",         "internet",                   "noun"),
    (407, "aula",             "class / lesson",             "noun"),
    (408, "professor",        "teacher (m.)",               "noun"),
    (409, "professora",       "teacher (f.)",               "noun"),
    (410, "aluno",            "student (m.)",               "noun"),

    # ── Health ────────────────────────────────────────────────────────────
    (411, "saúde",            "health",                     "noun"),
    (412, "médico",           "doctor (m.)",                "noun"),
    (413, "médica",           "doctor (f.)",                "noun"),
    (414, "enfermeiro",       "nurse (m.)",                 "noun"),
    (415, "doença",           "illness / disease",          "noun"),
    (416, "dor",              "pain / ache",                "noun"),
    (417, "febre",            "fever",                      "noun"),
    (418, "medicamento",      "medication / medicine",      "noun"),
    (419, "receita",          "prescription / recipe",      "noun"),
    (420, "consulta",         "appointment / consultation", "noun"),

    # ── Money & Shopping ──────────────────────────────────────────────────
    (421, "dinheiro",         "money",                      "noun"),
    (422, "euro",             "euro",                       "noun"),
    (423, "centavo",          "cent",                       "noun"),
    (424, "preço",            "price",                      "noun"),
    (425, "conta",            "bill / account",             "noun"),
    (426, "desconto",         "discount",                   "noun"),
    (427, "troco",            "change (coins)",             "noun"),
    (428, "cartão",           "card",                       "noun"),
    (429, "recibo",           "receipt",                    "noun"),
    (430, "compras",          "shopping",                   "noun"),

    # ── Common adverbs & expressions ─────────────────────────────────────
    (431, "muito",            "very / a lot",               "adverb"),
    (432, "pouco",            "a little / few",             "adverb"),
    (433, "mais",             "more",                       "adverb"),
    (434, "menos",            "less / fewer",               "adverb"),
    (435, "já",               "already / now",              "adverb"),
    (436, "ainda",            "still / yet",                "adverb"),
    (437, "só",               "only / just / alone",        "adverb"),
    (438, "também",           "also / too",                 "adverb"),
    (439, "bem",              "well",                       "adverb"),
    (440, "mal",              "badly",                      "adverb"),
    (441, "aqui",             "here",                       "adverb"),
    (442, "ali",              "there (near)",               "adverb"),
    (443, "lá",               "there (far)",                "adverb"),
    (444, "cima",             "up / above",                 "adverb"),
    (445, "baixo",            "down / below",               "adverb"),
    (446, "junto",            "together",                   "adverb"),
    (447, "perto",            "near / nearby",              "adverb"),
    (448, "longe",            "far (away)",                 "adverb"),
    (449, "depressa",         "quickly",                    "adverb"),
    (450, "devagar",          "slowly",                     "adverb"),

    # ── Articles (taught as vocabulary) ──────────────────────────────────
    (451, "o",                "the (m. singular)",          "phrase"),
    (452, "a",                "the (f. singular)",          "phrase"),
    (453, "os",               "the (m. plural)",            "phrase"),
    (454, "as",               "the (f. plural)",            "phrase"),
    (455, "um",               "a / an (m.)",                "phrase"),
    (456, "uma",              "a / an (f.)",                "phrase"),

    # ── Extra high-frequency nouns ────────────────────────────────────────
    (457, "nome",             "name",                       "noun"),
    (458, "número",           "number",                     "noun"),
    (459, "endereço",         "address",                    "noun"),
    (460, "país",             "country",                    "noun"),
    (461, "Portugal",         "Portugal",                   "noun"),
    (462, "Lisboa",           "Lisbon",                     "noun"),
    (463, "Porto",            "Porto",                      "noun"),
    (464, "língua",           "language",                   "noun"),
    (465, "português",        "Portuguese (language)",      "noun"),
    (466, "inglês",           "English (language)",         "noun"),
    (467, "palavra",          "word",                       "noun"),
    (468, "frase",            "sentence / phrase",          "noun"),
    (469, "pergunta",         "question",                   "noun"),
    (470, "resposta",         "answer / reply",             "noun"),
    (471, "informação",       "information",                "noun"),
    (472, "problema",         "problem",                    "noun"),
    (473, "ideia",            "idea",                       "noun"),
    (474, "razão",            "reason",                     "noun"),
    (475, "vez",              "time / occasion",            "noun"),
    (476, "coisa",            "thing",                      "noun"),
    (477, "lugar",            "place",                      "noun"),
    (478, "mundo",            "world",                      "noun"),
    (479, "vida",             "life",                       "noun"),
    (480, "caso",             "case",                       "noun"),

    # ── Leisure & Sport ───────────────────────────────────────────────────
    (481, "desporto",         "sport",                      "noun"),
    (482, "futebol",          "football / soccer",          "noun"),
    (483, "natação",          "swimming",                   "noun"),
    (484, "música",           "music",                      "noun"),
    (485, "cinema",           "cinema / movie theatre",     "noun"),
    (486, "teatro",           "theatre",                    "noun"),
    (487, "livro",            "book",                       "noun"),
    (488, "jornal",           "newspaper",                  "noun"),
    (489, "televisão",        "television",                 "noun"),
    (490, "filme",            "film / movie",               "noun"),
    (491, "música",           "song",                       "noun"),
    (492, "festa",            "party / celebration",        "noun"),
    (493, "férias",           "holidays / vacation",        "noun"),
    (494, "viagem",           "trip / journey",             "noun"),
    (495, "passeio",          "walk / outing",              "noun"),

    # ── Directions ───────────────────────────────────────────────────────
    (496, "esquerda",         "left",                       "noun"),
    (497, "direita",          "right",                      "noun"),
    (498, "frente",           "front / straight ahead",     "noun"),
    (499, "trás",             "back / behind",              "noun"),
    (500, "norte",            "north",                      "noun"),
    (501, "sul",              "south",                      "noun"),
    (502, "este",             "east",                       "noun"),
    (503, "oeste",            "west",                       "noun"),
    (504, "virar",            "to turn",                    "verb"),
    (505, "continuar",        "to continue / go straight",  "verb"),

    # ── More verbs ────────────────────────────────────────────────────────
    (506, "ter de",           "to have to / must",          "verb"),
    (507, "dever",            "should / ought to",          "verb"),
    (508, "pedir",            "to ask for / to order",      "verb"),
    (509, "mostrar",          "to show",                    "verb"),
    (510, "explicar",         "to explain",                 "verb"),
    (511, "ensinar",          "to teach",                   "verb"),
    (512, "aprender",         "to learn",                   "verb"),
    (513, "tentar",           "to try",                     "verb"),
    (514, "conseguir",        "to manage to / to get",      "verb"),
    (515, "deixar",           "to let / to leave behind",   "verb"),
    (516, "ganhar",           "to win / to earn",           "verb"),
    (517, "perder",           "to lose",                    "verb"),
    (518, "mudar",            "to change",                  "verb"),
    (519, "melhorar",         "to improve / to get better", "verb"),
    (520, "piorar",           "to get worse",               "verb"),
    (521, "conhecer",         "to know (a person/place)",   "verb"),
    (522, "visitar",          "to visit",                   "verb"),
    (523, "reservar",         "to book / to reserve",       "verb"),
    (524, "marcar",           "to mark / to book",          "verb"),
    (525, "confirmar",        "to confirm",                 "verb"),
    (526, "cancelar",         "to cancel",                  "verb"),
    (527, "preparar",         "to prepare",                 "verb"),
    (528, "organizar",        "to organise",                "verb"),
    (529, "entregar",         "to deliver / to hand in",    "verb"),
    (530, "receber",          "to receive",                 "verb"),

    # ── More adjectives ───────────────────────────────────────────────────
    (531, "importante",       "important",                  "adjective"),
    (532, "interessante",     "interesting",                "adjective"),
    (533, "diferente",        "different",                  "adjective"),
    (534, "mesmo",            "same",                       "adjective"),
    (535, "próximo",          "next / close",               "adjective"),
    (536, "último",           "last",                       "adjective"),
    (537, "primeiro",         "first",                      "adjective"),
    (538, "segundo",          "second",                     "adjective"),
    (539, "terceiro",         "third",                      "adjective"),
    (540, "certo",            "sure / certain",             "adjective"),
    (541, "possível",         "possible",                   "adjective"),
    (542, "necessário",       "necessary",                  "adjective"),
    (543, "especial",         "special",                    "adjective"),
    (544, "normal",           "normal",                     "adjective"),
    (545, "natural",          "natural",                    "adjective"),
    (546, "público",          "public",                     "adjective"),
    (547, "privado",          "private",                    "adjective"),
    (548, "agradável",        "pleasant / nice",            "adjective"),
    (549, "moderno",          "modern",                     "adjective"),
    (550, "antigo",           "old / ancient",              "adjective"),

    # ── More nouns (miscellaneous) ────────────────────────────────────────
    (551, "vezes",            "times (plural)",             "noun"),
    (552, "parte",            "part",                       "noun"),
    (553, "tipo",             "type / kind",                "noun"),
    (554, "forma",            "form / way",                 "noun"),
    (555, "lado",             "side",                       "noun"),
    (556, "nível",            "level",                      "noun"),
    (557, "serviço",          "service",                    "noun"),
    (558, "produto",          "product",                    "noun"),
    (559, "resultado",        "result",                     "noun"),
    (560, "exemplo",          "example",                    "noun"),
    (561, "período",          "period",                     "noun"),
    (562, "sistema",          "system",                     "noun"),
    (563, "processo",         "process",                    "noun"),
    (564, "programa",         "programme",                  "noun"),
    (565, "projecto",         "project",                    "noun"),
    (566, "centro",           "centre",                     "noun"),
    (567, "grupo",            "group",                      "noun"),
    (568, "equipa",           "team",                       "noun"),
    (569, "evento",           "event",                      "noun"),
    (570, "notícia",          "news",                       "noun"),
    (571, "mensagem",         "message",                    "noun"),
    (572, "carta",            "letter",                     "noun"),
    (573, "correio",          "mail / post office",         "noun"),
    (574, "pacote",           "package",                    "noun"),
    (575, "endereço",         "address",                    "noun"),
    (576, "código",           "code",                       "noun"),
    (577, "senha",            "password",                   "noun"),
    (578, "sinal",            "signal / sign",              "noun"),
    (579, "mapa",             "map",                        "noun"),
    (580, "caminho",          "path / way",                 "noun"),

    # ── Final batch ───────────────────────────────────────────────────────
    (581, "história",         "history / story",            "noun"),
    (582, "cultura",          "culture",                    "noun"),
    (583, "arte",             "art",                        "noun"),
    (584, "ciência",          "science",                    "noun"),
    (585, "tecnologia",       "technology",                 "noun"),
    (586, "natureza",         "nature",                     "noun"),
    (587, "ambiente",         "environment",                "noun"),
    (588, "energia",          "energy",                     "noun"),
    (589, "segurança",        "safety / security",          "noun"),
    (590, "liberdade",        "freedom / liberty",          "noun"),
    (591, "direito",          "right / law",                "noun"),
    (592, "dever",            "duty",                       "noun"),
    (593, "amor",             "love",                       "noun"),
    (594, "paz",              "peace",                      "noun"),
    (595, "guerra",           "war",                        "noun"),
    (596, "futuro",           "future",                     "noun"),
    (597, "passado",          "past",                       "noun"),
    (598, "presente",         "present",                    "noun"),
    (599, "sonho",            "dream",                      "noun"),
    (600, "esperança",        "hope",                       "noun"),
]
